tunnel: 2af4bef7-a71e-4515-8409-5f4c6868dab4
credentials-file: @CREDENTIALS@
metrics: 127.0.0.1:0
ingress:
  - hostname: sigong.rabbion.info
    service: http://127.0.0.1:8870
  - service: http_status:404
