"""Build a simplified, attributed physical river layer from the saved OSM response."""
import argparse
from collections import defaultdict
import gzip
from hashlib import sha256
import json
from pathlib import Path
from shapely import LineString, MultiLineString, line_merge

root=Path(__file__).resolve().parents[1]
parser=argparse.ArgumentParser(description=__doc__)
parser.add_argument('input',type=Path)
args=parser.parse_args()
raw=args.input.read_bytes()
data=json.loads(gzip.decompress(raw) if args.input.suffix=='.gz' else raw)
names={2899525:'압록강',3858130:'대동강',5454222:'청천강',5486141:'북한강',5488146:'임진강',5488151:'한강',5488155:'남한강',6970997:'두만강',17966007:'금강',17966016:'섬진강',19282570:'소양강'}
ways=defaultdict(dict)
refs=defaultdict(list)
for e in data['elements']:
    if e['type']=='relation':
        name=names[e['id']];refs[name].append('relation/'+str(e['id']))
        for m in e['members']:
            if m['type']=='way' and m.get('geometry') and m['role'] in ('','main_stream'):
                ways[name][m['ref']]=[(p['lon'],p['lat']) for p in m['geometry']]
    elif e['type']=='way':
        name=e['tags']['name'];refs[name].append('way/'+str(e['id']))
        ways[name][e['id']]=[(p['lon'],p['lat']) for p in e['geometry']]
rivers=[]
for name,lines in ways.items():
    merged=line_merge(MultiLineString([p for p in lines.values() if len(p)>1]))
    parts=[merged] if isinstance(merged,LineString) else list(merged.geoms)
    paths=[[[round(x,6),round(y,6)] for x,y in p.simplify(.0006).coords] for p in parts]
    rivers.append({'name':name,'osm':refs[name],'paths':paths})
source={'title':'OpenStreetMap river waterways','url':'https://www.openstreetmap.org/copyright','license':'ODbL-1.0',
        'licenseUrl':'https://opendatacommons.org/licenses/odbl/1-0/','osmTimestamp':data['osm3s']['timestamp_osm_base'],
        'rawSha256':sha256(gzip.decompress(raw) if args.input.suffix=='.gz' else raw).hexdigest(),
        'simplificationDegrees':.0006,'note':'현재 물길을 참고한 고정 지리 배경입니다. 강폭은 알아보기 쉽게 표현했으며 옛 물길이나 당시 강폭의 복원이 아닙니다.'}
target=root/'services/host/app/river-paths.js'
target.write_text('// Generated by scripts/build_river_display.py. River coordinates: © OpenStreetMap contributors, ODbL-1.0.\n'
    +'export const RIVER_SOURCE='+json.dumps(source,ensure_ascii=False,separators=(',',':'))+';\n'
    +'export const RIVERS='+json.dumps(rivers,ensure_ascii=False,separators=(',',':'))+';\n',encoding='utf8')
print(json.dumps({'rivers':len(rivers),'paths':sum(len(r['paths']) for r in rivers),'points':sum(len(p) for r in rivers for p in r['paths']),'bytes':target.stat().st_size}))
