"""Bake joined river banks without overlapping ribbons at tight bends."""
import base64
from hashlib import sha256
import json
import math
from pathlib import Path
import struct
from shapely import LineString,unary_union,constrained_delaunay_triangles

root=Path(__file__).resolve().parents[1];app=root/'services/host/app'
raw=(app/'river-paths.js').read_text(encoding='utf8')
rivers=json.loads(raw.split('export const RIVERS=')[1].rstrip(';\n'))
merc=lambda lat:math.log(math.tan(math.pi/4+math.radians(lat)/2))
scale=1600/(merc(43.5)-merc(33));center_y=(merc(43.5)+merc(33))/2
project=lambda x,y:((math.radians(x)-math.radians(127.5))*scale,-(merc(y)-center_y)*scale)
water=[];outer=[]
for river in rivers:
    width=.62 if river['name'] in ['북한강','소양강','남한강','임진강'] else .92
    for path in river['paths']:
        line=LineString([project(*p) for p in path]).simplify(.15)
        water.append(line.buffer(width,quad_segs=2));outer.append(line.buffer(width+.18,quad_segs=2))
water=unary_union(water);banks=unary_union(outer).difference(water)
result={}
for name,polygon in [('water',water),('banks',banks)]:
    vertices=[];indices=[];lookup={}
    def triangle(a,b,c):
        points=[a,b,c];lengths=[math.dist(points[i],points[(i+1)%3]) for i in range(3)]
        if max(lengths)>4:
            i=lengths.index(max(lengths));p=points[i];q=points[(i+1)%3];r=points[(i+2)%3];m=((p[0]+q[0])/2,(p[1]+q[1])/2)
            triangle(p,m,r);triangle(m,q,r);return
        if sum(points[i][0]*points[(i+1)%3][1]-points[(i+1)%3][0]*points[i][1] for i in range(3))>0:points.reverse()
        for p in points:
            key=tuple(round(v,5) for v in p)
            if key not in lookup:lookup[key]=len(vertices)//2;vertices.extend(key)
            indices.append(lookup[key])
    for t in constrained_delaunay_triangles(polygon).geoms:triangle(*list(t.exterior.coords)[:3])
    encode=lambda values,kind:base64.b64encode(struct.pack('<'+kind*len(values),*values)).decode()
    assert len(vertices)//2<65536
    result[name]={'xz':encode(vertices,'f'),'indices':encode(indices,'H'),'triangles':len(indices)//3}
(app/'river-grid.js').write_text('// Generated by scripts/build_river_mesh.py. Derived river coordinates: © OpenStreetMap contributors, ODbL-1.0.\n'
    +'export const RIVER_MESH_SOURCE="'+sha256(raw.encode()).hexdigest()+'";\n'
    +'export const RIVER_MESH='+json.dumps(result,separators=(',',':'))+';\n',encoding='utf8')
print(json.dumps({k:{'triangles':v['triangles']} for k,v in result.items()}))
