"""Pre-clip an even terrain grid to the existing coastline; no browser triangulation."""
import base64
from hashlib import sha256
import json
import math
from pathlib import Path
import struct
from shapely import Polygon,Point,box,constrained_delaunay_triangles

root=Path(__file__).resolve().parents[1]
app=root/'services/host/app'
outline=json.loads((app/'korea-outline.json').read_text(encoding='utf8'))
geography=json.loads((app/'history-geography.json').read_text(encoding='utf8'))
merc=lambda lat:math.log(math.tan(math.pi/4+math.radians(lat)/2))
scale=1600/(merc(43.5)-merc(33));center_y=(merc(43.5)+merc(33))/2
project=lambda x,y:((math.radians(x)-math.radians(127.5))*scale,-(merc(y)-center_y)*scale)
polygons=[Polygon(p[0]) for p in outline['geometry']['coordinates']]
polygons=[p for p in polygons if not any(p.contains(Point(i['lon'],i['lat'])) for i in geography['islands'])]
for island in geography['islands']:
    g=island['geometry'];polygons.extend(Polygon(p[0]) for p in ([g['coordinates']] if g['type']=='Polygon' else g['coordinates']))
vertices=[];indices=[];lookup={};area=0;source_area=0
for polygon in polygons:
    p=Polygon([project(x,y) for x,y in polygon.exterior.coords]);source_area+=p.area
    x0,z0,x1,z1=p.bounds;size=10
    for x in range(math.floor(x0/size),math.ceil(x1/size)):
        for z in range(math.floor(z0/size),math.ceil(z1/size)):
            clipped=p.intersection(box(x*size,z*size,(x+1)*size,(z+1)*size))
            if clipped.is_empty or clipped.area<1e-9:continue
            for t in constrained_delaunay_triangles(clipped).geoms:
                if t.area<1e-10:continue
                area+=t.area;coords=list(t.exterior.coords)[:3]
                if sum(coords[i][0]*coords[(i+1)%3][1]-coords[(i+1)%3][0]*coords[i][1] for i in range(3))>0:coords.reverse()
                for a,b in coords:
                    key=(round(a,5),round(b,5))
                    if key not in lookup:lookup[key]=len(vertices)//2;vertices.extend(key)
                    indices.append(lookup[key])
assert abs(area/source_area-1)<1e-6
encode=lambda values,kind:base64.b64encode(struct.pack('<'+kind*len(values),*values)).decode()
meta={'cellSize':10,'vertices':len(vertices)//2,'triangles':len(indices)//3,'areaRatio':area/source_area,
      'outlineSha256':sha256((app/'korea-outline.json').read_bytes()).hexdigest(),
      'geographySha256':sha256((app/'history-geography.json').read_bytes()).hexdigest()}
(app/'terrain-grid.js').write_text('// Generated by scripts/build_terrain_grid.py from the existing coastline.\n'
    +'export const GRID_INFO='+json.dumps(meta)+';\n'
    +'export const GRID_XZ="'+encode(vertices,'f')+'";\n'
    +'export const GRID_INDICES="'+encode(indices,'H')+'";\n',encoding='utf8')
print(json.dumps(meta))
