import assert from 'node:assert/strict';
import {sceneryPeriod,sceneryRecipe} from '../services/host/app/scenery-period.js';
const site={latitude:35,seed:2},northern={...site,latitude:40};
const recipe={id:'scenery-village:4:0',archetype:'rural_cottage',scale:.3};
assert.equal(sceneryPeriod(-2000).fields,false);
assert.equal(sceneryPeriod(-500).fields,true);
assert.equal(sceneryRecipe(recipe,sceneryPeriod(-500),site).archetype,'rural_hut');
assert.equal(sceneryRecipe({...recipe,archetype:'handcart'},sceneryPeriod(-500),site),null);
assert.equal(sceneryPeriod(1592).id,sceneryPeriod(1597).id);
assert.equal(sceneryPeriod(1500).tigers,true);
assert.equal(sceneryPeriod(2000).tigers,false);
assert.equal(sceneryRecipe({...recipe,archetype:'human'},sceneryPeriod(2000),site).archetype,'field_worker');
const houses=n=>Array.from({length:100},(_,seed)=>sceneryRecipe(recipe,sceneryPeriod(n),{...site,seed}).archetype);
assert.ok(houses(1975).includes('rural_cottage')&&houses(1975).includes('rural_metal'));
assert.ok(houses(1980).filter(h=>h.startsWith('rural_')&&h!=='rural_cottage').length>houses(1975).filter(h=>h!=='rural_cottage').length);
assert.equal(sceneryRecipe(recipe,sceneryPeriod(2000),northern).archetype,'rural_cottage','Southern modernization sources do not imply a northern roof campaign');
assert.equal(sceneryRecipe({...recipe,archetype:'handcart'},sceneryPeriod(1975),site).archetype,'handcart');
assert.equal(sceneryRecipe({...recipe,archetype:'handcart'},sceneryPeriod(1980),site).archetype,'farm_tractor');
console.log('PASS: era settings, mixed roofs, tools, anonymous people, northern source scope and wildlife display');
