import assert from 'node:assert/strict';
import {sceneryPeriod,sceneryRecipe} from '../services/host/app/scenery-period.js';
const site={latitude:35,seed:2},northern={...site,latitude:40};
const recipe={id:'scenery-village:4:0',archetype:'rural_cottage',scale:.3};
assert.equal(sceneryPeriod(-2000).fields,false);
assert.equal(sceneryPeriod(-500).fields,true);
assert.match(sceneryRecipe(recipe,sceneryPeriod(-500),site).archetype,/^era_early_house_/);
assert.equal(sceneryRecipe({...recipe,archetype:'handcart'},sceneryPeriod(-500),site),null);
assert.equal(sceneryPeriod(1592).id,sceneryPeriod(1597).id);
assert.equal(sceneryPeriod(1592),sceneryPeriod(1597),'Same era shares a stable period object');
assert.notEqual(sceneryPeriod(600).id,sceneryPeriod(1200).id);
assert.notEqual(sceneryPeriod(1200).id,sceneryPeriod(1600).id);
assert.equal(sceneryPeriod(1500).tigers,true);
assert.equal(sceneryPeriod(2000).tigers,false);
assert.equal(sceneryRecipe({...recipe,archetype:'human'},sceneryPeriod(2000),site).archetype,'figure_modern_commoner');
const personAt=year=>sceneryRecipe({...recipe,archetype:'human'},sceneryPeriod(year),site).archetype;
assert.equal(personAt(600),'figure_three_kingdoms_commoner');
assert.equal(personAt(1200),'figure_goryeo_commoner');
assert.equal(personAt(1894),'figure_joseon_commoner');
assert.equal(personAt(1895),'figure_transition_commoner');
assert.equal(personAt(1944),'figure_transition_commoner');
assert.equal(personAt(1945),'figure_modern_commoner');
assert.notEqual(sceneryPeriod(1894),sceneryPeriod(1895));
assert.notEqual(sceneryPeriod(1944),sceneryPeriod(1945));
const houses=n=>Array.from({length:100},(_,seed)=>sceneryRecipe(recipe,sceneryPeriod(n),{...site,seed}).archetype);
assert.ok(houses(1975).includes('rural_cottage')&&houses(1975).includes('rural_metal'));
assert.ok(houses(1980).filter(h=>h.startsWith('rural_')&&h!=='rural_cottage').length>houses(1975).filter(h=>h!=='rural_cottage').length);
assert.doesNotMatch(sceneryRecipe(recipe,sceneryPeriod(2000),northern).archetype,/^era_joseon_house_/,'Modern northern scenery must not revert to 1700');
assert.notEqual(sceneryRecipe({...recipe,archetype:'rural_hut'},sceneryPeriod(2000),northern).archetype,'rural_hut',
  'Neutral northern scenery does not bring back prehistoric hut silhouettes');
assert.equal(sceneryRecipe({...recipe,archetype:'handcart'},sceneryPeriod(1975),site).archetype,'handcart');
assert.equal(sceneryRecipe({...recipe,archetype:'handcart'},sceneryPeriod(1980),site).archetype,'farm_tractor');
console.log('PASS: era settings, mixed roofs, tools, anonymous people, northern source scope and wildlife display');
