import assert from 'node:assert/strict';
import {contextAt, datedClaims} from '../services/host/app/chronicle.js';

const person={id:'person-example',type:'Person',label:'인물'};
const event={id:'event-example',type:'Event',label:'사건'};
const claim=(id,predicate,object,source='src-a',subject=person.id)=>({id,subject,predicate:'syj:'+predicate,object,fromSource:source});
const birth=claim('birth','bornIn',{kind:'year',value:1390});
const death=claim('death','diedIn',{kind:'year',value:1450});
const data=claims=>({entities:[person,event],claims});
assert.equal(contextAt(data([birth,death]),1420).people.length,1);
assert.equal(contextAt(data([birth,death]),1451).people.length,0);
assert.equal(contextAt(data([birth]),1420).people.length,0,'Missing death cannot mean indefinite survival');
assert.equal(contextAt(data([birth,{...death,fromSource:'src-b'}]),1420).people.length,0,'Lifespan ends cannot silently join across sources');
const reign=claim('reign','reignedIn',{kind:'time',id:'ts-reign',verbatim:'1418–1450',earliest:1418,latest:1450});
assert.equal(contextAt(data([reign]),1420).people[0].periods[0].label,'재위');
assert.equal(contextAt(data([reign]),1410).people.length,0);
const eventDate=claim('date','occurredIn',{kind:'time',id:'ts-event',verbatim:'그 해'},'src-a',event.id);
assert.equal(contextAt(data([eventDate]),1446).events.length,0,'An original date without conversion cannot acquire an invented year');
const conversion=claim('conversion','convertsTo',{kind:'year',value:1446},'src-b','ts-event');
const converted=data([eventDate,conversion]);
assert.equal(contextAt(converted,1446).events[0].current,true);
assert.equal(contextAt(converted,1440).events[0].current,false,'Nearby does not mean occurring in the selected year');
assert.equal(contextAt(converted,1390).events.length,0);
assert.equal(contextAt(converted,1390).next,1446);
assert.equal(datedClaims(converted)[0].basis.length,2,'Original date and conversion both retain evidence');
assert.equal(contextAt(data([]),1446).people.length,0);
assert.equal(contextAt(data([]),1446).events.length,0);
const membership=claim('member','memberOf',{kind:'entity',id:'polity-example'});
assert.equal(contextAt(data([birth,death,membership]),1395).people[0].relations.length,0,'Birth is not the start of membership');
const king=claim('king','isKingOf',{kind:'entity',id:'polity-example'});
assert.equal(contextAt(data([birth,death,reign,king]),1410).people[0].relations.length,0,'Living before accession does not mean reigning');
assert.equal(contextAt(data([birth,death,reign,king]),1420).people[0].relations.length,1);
const duration={...eventDate,object:{kind:'time',id:'ts-war',earliest:1443,latest:1446}};
const start={...eventDate,id:'date-start',object:{kind:'year',value:1443}};
assert.equal(contextAt(data([duration,start]),1444).events.length,1,'A duration and its start do not duplicate the same event');
const uncertainBirth={...birth,object:{kind:'time',id:'ts-birth',earliest:1390,latest:1400}};
assert.equal(contextAt(data([uncertainBirth,death]),1395).people.length,0,'Uncertain birth is not definite survival');
console.log('PASS: lifespans, source separation, reign, unknown dates, conversion evidence, nearby events and empty selection');
